name: urbspicta
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  simple_animations: ^1.3.4
  page_transition: ^1.1.5
  sliding_up_panel: ^0.3.6
  flare_flutter: ^2.0.1
  flutter_animation_progress_bar: ^1.0.0

  geolocator: ^4.0.0
  google_maps_flutter:
  google_map_polyline: ^0.2.0+1

  dio:
  http: ^0.12.0+4
  permission_handler: ^4.2.0
  google_api_availability: ^2.0.2
  json_annotation: ^3.0.1
  url_launcher: ^3.0.3

  carousel_slider: ^1.3.0
  dots_indicator: ^1.1.0

dev_dependencies:
  build_runner: ^1.7.3
  json_serializable: ^3.2.5
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Light.ttf
          weight: 200
        - asset: fonts/Montserrat-Medium.ttf
          weight: 400
        - asset: fonts/Montserrat-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-Medium.ttf